name = "Integer number game"
version = "0.1.0"
extra_files = "extras"
intro = "src/game/intro.lean"

[[worlds]]
name = "Definitions"
id = 1
levels = [
	"src/game/basic/level01.lean",
	"src/game/basic/level02.lean"

]

[[worlds]]
name = "Operations"
id = 2
parents = [1]
levels = [
	"src/game/sums/level01.lean"
]

[[worlds]]
name = "Algebraic Structure"
id = 3
parents = [1]
levels = [
	"src/game/products/level01.lean"
]


